apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: 
  name: myapp-hpa
  namespace: default 
spec: 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myapp
  minReplicas: 1                #minimum numbers of replicas
  maxReplicas: 10               #maximum numbers of replicas 
  metrics: 
    - type: Resource
      resource: 
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50  #target cpu utilization percentage
